<?php
define("SIMPLE_MATHS_CATPCHA_BASE_ID", "contact-form-simple-maths-captcha");
define("SIMPLE_MATHS_CAPTCHA_PROBLEM_INVALID_AFTER_TIME_MS", 15000);
define("SIMPLE_MATHS_CAPTCHA_PROBLEM_VALIDATION_SLACK_TIME", 1500);
