<?php
$MY_NAME_FIRST = "Viktor";
$MY_NAME_LAST_SHORT = "Chin";
$MY_NAME_LAST_FULL = $MY_NAME_LAST_SHORT . "-Kon-Sung";
$MY_NAME_SHORT = $MY_NAME_FIRST . " " . $MY_NAME_LAST_SHORT;
$MY_NAME_LONG = $MY_NAME_FIRST . " " . $MY_NAME_LAST_FULL;
